export const testimonials = [
  {
    id: 1,
    quote:
      "Pulse AI has fundamentally changed how our engineering team ships. The smart automation alone saved us 15 hours per dev weekly.",
    author: {
      name: "Sarah Chen",
      role: "Head of Product",
      company: "Vercel",
      avatar:
        "https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    },
  },
  {
    id: 2,
    quote: "We've cut onboarding time by more than 60%. New team members become productive in days instead of weeks.",
    author: {
      name: "Michael Torres",
      role: "Engineering Manager",
      company: "Stripe",
      avatar:
        "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    },
  },
  {
    id: 3,
    quote:
      "The insights generated by Pulse AI helped us identify bottlenecks we didn't even know existed. Our team's velocity increased dramatically.",
    author: {
      name: "Emily Rodriguez",
      role: "VP of Engineering",
      company: "Notion",
      avatar:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    },
  },
];
